#!/bin/bash
#create_script 
if [[ ! $1 ]]; then
  echo "Missing argument"
  exit 1
fi
scriptname="$1"
bindir="${HOME}/bin"
filename="${bindir}/$1"

if [[ -e $filename ]]; then
  echo " File ${filename} already exists"
  exit 1
fi

if type "$scriptname" > /dev/null 2>&1; then 
    echo "there is already a command with name ${scriptname}"
    exit 1
fi

 #check if bin directory exists 
 if [[ ! -d $bindir ]]; then
    #if not: create bin directory
    if mkdir "$bindir"; then
        echo "created ${bindir}"
    else
        echo "Could not create ${bindir}"
        exit 1
    fi 
fi
#create a script with a single line
echo '#!/bin/bash' > "$filename"
# add executable permission
chmod u+x "$filename"
# open with editor
if [[ $EDITOR ]]; then
    $EDITOR "$filename"
else 
    echo "script created; not starting editor couse \$EDITOR is not set"
fi
echo "End of code"
exit 0