#!/bin/bash

if [[ ! $1 ]]; then
    echo "Need first argument" >&2
    exit 1
fi
found=""
#read up to first match



while read -r; do 
    if [[ ! $found ]]; then
        if [[ $REPLY=~1 ]]; then
            found="yup"
        else 
            continue
        fi
    fi
    echo "$REPLY"
done
exit 0